### ISSUE TITLE
一键安装脚本

### ISSUE THREAD

**Issue by recolic** [rootmelo92118/v2ray-edit-from-233boy#2]
原233boy提供的版本，有一个一键安装的脚本 `bash <(curl -s -L https://git.io/v2ray.sh)` 。它很方便。
我们这个版本是不是也应该提供一个一键脚本。

尽管我也是一个相当熟练的linux多年用户，知道如何安装此脚本。但人类还是懒惰的。。

**Comment by rootmelo92118** [comment]
謝謝，已經加入相關內容
