### ISSUE TITLE
自动/低成本同步上游

### ISSUE THREAD

**Issue by recolic** [rootmelo92118/v2ray-edit-from-233boy#3]
当上游233boy的仓库出现新更改时，我们每次都手动pull，这不是一个长久的解决方案。

我们应当有一种自动化或半自动化的方式，能够自动或一键同步上游的最新更新。

具体的操作是：我们写一个脚本，自动将233boy/v2ray仓库中的破坏网络中立性的配置去除。然后每隔一段时间（例如24h），自动`git clone 233boy ; ./fix.sh ; git push THIS_REPO --force`

**Comment by rootmelo92118** [comment]
我沒有這麼做的原因是上游這一個倉庫基本上已經停止維護了只是代碼還能用

**Comment by rootmelo92118** [comment]
所以不存在我要頻繁去更新這件事
